### ISSUE TITLE
Undocumented return info for /wallet/assets

### ISSUE THREAD

**Issue by ageorge95** [infinex-exchange/api-docs#9]
Recently there is another piece of information returned for the` /wallet/assets` endpoint.
Ex:
```
'1INCH': {'icon_url': '/ico/1inch.svg',
          'max_prec': 18,
          'name': '1INCH'}
```
What dioes `max_prec` mean ? I could not find this parameter in the documentation.

**Comment by infinex-exchange** [comment]
This is the maximum number of decimal places that a given coin can have, taking into account all possible deposit and withdrawal networks.
